apiVersion: apps/v1
kind: Deployment #The kind of object I'm creating
metadata:
  name: p1 #arbitrary but important name
spec:
  replicas: 3 #3 replica pods will be made for this deployment
  selector: #the selector and labels should match the ones in the service.yaml to create a pairing
    matchLabels:
      app: p1
  template:
    metadata:
      labels:
        app: p1
    spec:
      containers: #here's where we define info about the container that this deployment will spin up
        - name: p1 #this will be the name of the container
          image: 296271419447.dkr.ecr.us-east-2.amazonaws.com/testing-ben:latest #The image we want to base the container off of
          ports:
            - containerPort: 8080 #the container will run on port 8080 in the cluster
---
apiVersion: apps/v1
kind: Deployment #The kind of object I'm creating
metadata:
  name: lambda #arbitrary but important name
spec:
  replicas: 1 #3 replica pods will be made for this deployment
  selector: #the selector and labels should match the ones in the service.yaml to create a pairing
    matchLabels:
      app: lambda
  template:
    metadata:
      labels:
        app: lambda
    spec:
      containers: #here's where we define info about the container that this deployment will spin up
        - name: lambda #this will be the name of the container
          image: 296271419447.dkr.ecr.us-east-2.amazonaws.com/lamba-get-items:latest #The image we want to base the container off of
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: p1
  ports:
    - port: 80 #directly specifying a port this time
      targetPort: 5000 #in accordance with the application.properties
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: get-items-lambda
spec:
  selector:
    app: lambda
  ports:
    - port: 80 #directly specifying a port this time
      targetPort: 8080 #in accordance with the application.properties
  type: LoadBalancer
