apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer #This time we'll provision a LoadBalancer (instead of NodePort). Better for production!
  selector:
    app: api
  ports:
    - port: 7262 #directly specifying a port this time
      targetPort: 5000 #in accordance with the application.properties